FROM node:22

WORKDIR /app

# Installer NestJS CLI globalement
RUN npm install -g @nestjs/cli

# Copier les fichiers package
COPY app/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY app/ .

# Exposer le port
EXPOSE 3000

# Commande pour le développement avec hot reload
CMD ["npm", "run", "start:dev"]